name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Sanitize Tag Name
        run: |
          tag_name=$(echo "${github.event.release.tag_name}" | sed -e 's/[^a-zA-Z0-9.-_]/_/g')
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-podcast-sponsor-block:latest
            ${{ secrets.DOCKER_USERNAME }}/go-podcast-sponsor-block:${{ env.TAG_NAME }}